name: Portfolio CI/CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            patil9907/portfolio:latest
            patil9907/portfolio:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl set image deployment/portfolio-deployment portfolio=patil9907/portfolio:${{ github.sha }}
          kubectl rollout status deployment/portfolio-deployment